# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-03 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nice_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Input',
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.Field')),
                ('value', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.Field')),
                ('description', models.CharField(max_length=200)),
                ('value', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Irrigation',
            fields=[
                ('field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.Field')),
                ('value', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pesticide',
            fields=[
                ('field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.Field')),
                ('value', models.FloatField(default=0)),
            ],
        ),
    ]
